export const ACT_SAVE_ARCHIVE = 'SAVE_ARCHIVE';
export const ACT_OPEN_ARCHIVE = 'OPEN_ARCHIVE';
export const ACT_CHECK_PASSED_FILE = 'CHECK_PASSED_FILE';
export const ACT_SHOW_PATH_IN_FOLDER = 'SHOW_PATH_IN_FOLDER';
export const ACT_ARCHIVE_SEND_EMAIL = 'ARCHIVE_SEND_EMAIL';
export const ACT_IMPORT_FORM = 'IMPORT_FORM';
