"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ACT_CANCEL_CHECK_FOR_UPDATES = 'CANCEL_CHECK_FOR_UPDATES';
exports.ACT_CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
exports.ACT_GET_FORM = 'GET_FORM';
exports.ACT_GET_FORMS_INDEX = 'GET_FORMS_INDEX';
exports.ACT_UPDATE_FORMS = 'UPDATE_FORMS';
exports.ACT_CANCEL_UPDATE_FORMS = 'CANCEL_UPDATE_FORMS';
exports.ACT_IMPORT_FORM = 'IMPORT_FORM';
