export const ACT_CANCEL_CHECK_FOR_UPDATES = 'CANCEL_CHECK_FOR_UPDATES';
export const ACT_CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
export const ACT_GET_FORM = 'GET_FORM';
export const ACT_GET_FORMS_INDEX = 'GET_FORMS_INDEX';
export const ACT_UPDATE_FORMS = 'UPDATE_FORMS';
export const ACT_CANCEL_UPDATE_FORMS = 'CANCEL_UPDATE_FORMS';

