module.exports = {
    ACT_SAVE_ARCHIVE: 'SAVE_ARCHIVE',
    ACT_OPEN_ARCHIVE: 'OPEN_ARCHIVE',
    ACT_CHECK_PASSED_FILE: 'CHECK_PASSED_FILE',
    ACT_SHOW_PATH_IN_FOLDER: 'SHOW_PATH_IN_FOLDER',
    ACT_ARCHIVE_SEND_EMAIL: 'ARCHIVE_SEND_EMAIL',
    ACT_IMPORT_FORM: 'IMPORT_FORM',
};
