export const ACT_CANCEL_CHECK_FOR_UPDATES: string = 'CANCEL_CHECK_FOR_UPDATES';
export const ACT_CHECK_FOR_UPDATES: string = 'CHECK_FOR_UPDATES';
export const ACT_GET_FORM: string = 'GET_FORM';
export const ACT_GET_FORMS_INDEX: string = 'GET_FORMS_INDEX';
export const ACT_UPDATE_FORMS: string = 'UPDATE_FORMS';
export const ACT_CANCEL_UPDATE_FORMS: string = 'CANCEL_UPDATE_FORMS';
export const ACT_FORM_TEMPLATE_SELECT_REPOSITORY: string = 'ACT_FORM_TEMPLATE_SELECT_REPOSITORY';


