module.exports = {
	ACT_CANCEL_CHECK_FOR_UPDATES: 'CANCEL_CHECK_FOR_UPDATES',
	ACT_CHECK_FOR_UPDATES: 'CHECK_FOR_UPDATES',
	ACT_GET_FORM: 'GET_FORM',
	ACT_GET_FORMS_INDEX: 'GET_FORMS_INDEX',
	ACT_UPDATE_FORMS: 'UPDATE_FORMS',
	ACT_CANCEL_UPDATE_FORMS: 'CANCEL_UPDATE_FORMS',
};

